#!/usr/bin/env bash
len() { L=$#; }
if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else
	while read NBR
	do
		R=$(factor $NBR)
		S=($(factor $NBR))
		a=${S[1]}
		len $R
		c=0
		if [ $L -eq 3 ]
		then
			b=${S[2]}
		else
			echo "$S" | tr ':' ''
		fi
		d=$(echo "$S" | tr ':' '=')
		ch=$(echo "if($b > $a) 1 else 0" | bc)
		if [ $ch -eq 1 ]
		then
			echo "$d$a*$b"
		else
			echo "$d$b*$a"
		fi
	done < $1
fi
